stages :
    - build
    - deploy
build_staging :
    stage: build
    script:
          - source /etc/profile
          - echo "java Build..."
          - pwd
#          - /opt/ci-shell/2.0/to-git --rsync-from=$CI_PROJECT_DIR/src/main/groovy/crontab/  --git-repository=online/script.git  --clean=false
          - rsync -av src/main/groovy/crontab/*/* webserver@192.168.2.9:/empty/crontab/
          - rsync -av src/main/groovy/crontab/crontab.txt webserver@192.168.2.9:/empty/crontab/
          - ssh root@101.201.68.1  "chmod -Rf 755 /empty/crontab/* && cat /empty/crontab/crontab.txt > /etc/cron.d/root.cron"
          - echo "java Build success"
    only :
        - master
    tags :
        - java-shell